assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE02SHSP-SP001-07-FLORTJ000
stream:
  method: telemetered
  name: flort_sample
workflow_config:
  schedule: 0 0 * * *
